const mapping = {
    "ProbillNo":"ProbillNo",
    "OrderNo":"OrderNo",
    "HazMat":"HazMat",
    "Truckload":"Truckload",
    "cu.ft":"cu.ft",
    "lbs":"lbs",
    "m3":"m3",
    "pcs":"pcs",
    "skids":"skids",
    "truck load":"truck_load",
    "PUNumber":"PUNumber",
    "Comment":"Comment",
    "Location_pickuploc":"Location_pickuploc",
    "Address1_pickuploc":"Address1_pickuploc",
    "Address2_pickuploc":"Address2_pickuploc",
    "City_pickuploc":"City_pickuploc",
    "PostalCode_pickuploc":"PostalCode_pickuploc",
    "Geocode_pickuploc":"Geocode_pickuploc",
    "Prov_pickuploc":"Prov_pickuploc",
    "Country_pickuploc":"Country_pickuploc",
    "Location_deliveryloc":"Location_deliveryloc",
    "Address1_deliveryloc":"Address1_deliveryloc",
    "Address2_deliveryloc":"Address2_deliveryloc",
    "City_deliveryloc":"City_deliveryloc",
    "PostalCode_deliveryloc":"PostalCode_deliveryloc",
    "Geocode_deliveryloc":"Geocode_deliveryloc",
    "Prov_deliveryloc":"Prov_deliveryloc",
    "Country_deliveryloc":"Country_deliveryloc",
    "PONo":"PONo",
    "Equipment":"Equipment",
    "ProbillCount":"ProbillCount",
    "Pickup_date":"Pick Date",
    "Delivery_date":"Delivery Date",
    "PickUp_StartTime":"Pick up Window Start",
    "PickUp_EndTime":"Pick up Window End",
    "Deliver_StartTime":"Delivery Window Start",
    "Deliver_EndTime":"Delivery Window End"
};
module.exports = JSON.stringify(mapping);